name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies for admin panel
      run: |
        cd admin-panel # Adjust if the admin panel is in a different directory
        npm ci

    - name: Build admin panel project
      run: |
        cd admin-panel # Adjust if needed
        npm run build

    - name: Run tests for admin panel
      run: |
        cd admin-panel # Adjust if needed
        npm test
